import os

DEFAULT_ROOT_DIRECTORY = ".."
DEFAULT_RESOURCES_DIRECTORY_PATH = os.path.join(DEFAULT_ROOT_DIRECTORY, "resources")
DEFAULT_LOGS_DIRECTORY_PATH = os.path.join(DEFAULT_RESOURCES_DIRECTORY_PATH, "logs")
DEFAULT_CONFIG_FILENAME = "configs.ini"
DEFAULT_OUTDATED_OPTIONS_SECTION = "Outdated Options"
